### ISSUE TITLE
[MINOR] Review for Professor That Doesn't Exist

### ISSUE THREAD

**Issue by ccforbes** [CourseVisor/CourseVisor#45]
I created a review for CSE 142. I entered "Baby Yoda" for the instructor. And the review was accepted. I think it's in the best interest of the user to know that the professor actually exists in the university

**Comment by albertli354** [comment]
### This is not a real bug
When we scripting the whole UW course database, we found there are courses like special topics that change their instructors constantly. There are also situations in which instructor names still do not appear in UW's database. In this case, we want to give users the freedom to create their own professor names to deal with such situations. We acknowledge that it is not the perfect solution, and we are open to more opinions on how to address the problems.
