### ISSUE TITLE
[MINOR] Gibberish allowed for professor name

### ISSUE THREAD

**Issue by tfpenner** [CourseVisor/CourseVisor#46]
Describe the bug
Gibberish instructor name accepted as valid.

To Reproduce
When filling in the "Instructor" text field for a course review, enter a string of numbers and letters: "Fsfse348213478931247". This was accepted as a valid instructor

Expected behavior
Form rejects field, not allowing the user to submit the form.

Screenshot
This is the course review of the instructor after I
<img width="1082" alt="Screen Shot 2019-12-05 at 5 42 36 PM" src="https://user-images.githubusercontent.com/53621324/70288503-bbadaf80-1786-11ea-84a4-614ff807cabf.png">
 submitted the form

Desktop (please complete the following information):
Chrome

**Comment by albertli354** [comment]
duplicated issue, see #45
