### ISSUE TITLE
[MINOR] Text for Comment reviews does not wrap

### ISSUE THREAD

**Issue by anuraagpolisetty** [CourseVisor/CourseVisor#47]
**Description**
I created a 3000-character long comment in CSE 142 that doesn't wrap text and continues off into the side of the page.

**Steps to recreate**
1. Search up CSE 142 in Course lists
2. Click on 'I Don't Know Who The Instructor Is It's Been 3 Years Man Idk Who It Is Now Sorry'
3. Scroll down to see Comment

**Expected Behavior**
I expected the text to wrap so that I can see the whole content of the comment within the page instead of scrolling to the right

**Desktop**
Browser: Chrome

**Comment by albertli354** [comment]
Bug fixed. Text can render properly.
