### ISSUE TITLE
[MINOR] html tag input makes page loading

### ISSUE THREAD

**Issue by deepforce** [CourseVisor/CourseVisor#48]
**Describe the bug**
Input html tags in instructor input box will cause page loading

**To Reproduce**
1. Go to 'Submit New Review'
2. Type </> in instructor inputbox
3. See error

**Expected behavior**
Invalid input reminder.

**Screenshots**
![image](https://user-images.githubusercontent.com/10813672/70293528-64630b80-1795-11ea-9500-379f8e47f083.png)
![image](https://user-images.githubusercontent.com/10813672/70293561-7e045300-1795-11ea-8b63-9a3cb5546d9f.png)

**Desktop (please complete the following information):**
 - OS: [OSX]
 - Browser [chrome]

**Comment by albertli354** [comment]
Bug fixed. Instructor name fields cannot contain any illegal characters.
