### ISSUE TITLE
[MAJOR] Same user can post reviews on the same professor multiple times

### ISSUE THREAD

**Issue by wochen96** [CourseVisor/CourseVisor#49]
As the same user I can keep creating a new review for the same professor. I feel like this is a major issue, because it can cause people to spam reviews to make the ratings seem good or bad.

**Comment by albertli354** [comment]
### This is not a real bug
Thanks for your feedback. After careful consideration, we think this is not an actual bug for our website. As a student-centered application, we want to give users the freedom to create their own reviews without any interference. It is part of the product philosophy and mission that a student-centered information system should be decided completely by students themselves.
