### ISSUE TITLE
[MINOR]

### ISSUE THREAD

**Issue by laurens24** [CourseVisor/CourseVisor#50]
**Issue description**
Purple background color doesn't reach all the way to the bottom of the page

**To reproduce**
1. Sign up for a new account
2. Created a profile with username, password, and email all "lauren"
3. Error message comes up saying "email address is badly formatted" which is good
4. Scroll down, and there is now white space that cuts off the text reading "Already a member? Log in"
5. Noticed the issue worsens if I zoom in further on my browser and is fixed if I zoom out

![image](https://user-images.githubusercontent.com/13319713/70383295-48d83c00-1920-11ea-894f-7c3684166ef6.png)

**Device information**
 - Macbook Pro 13" screen
 - Google Chrome

**Comment by albertli354** [comment]
The page is now rendered properly
