### ISSUE TITLE
[MINOR] Search results for whitespace turns up empty

### ISSUE THREAD

**Issue by anuraagpolisetty** [CourseVisor/CourseVisor#51]
When searching for a course, if a user inputs a string of pure whitespace (which just spaces) the result is just an empty page, with no feedback as to what results show up or whether it didn't match anything. This could be a problem because the user receives no feedback as to what their search returns. 

Steps to recreate:
1. Go to search bar.
2. Type in "     " (4 spaces)
3. Hit enter
4. View blank page

**Comment by albertli354** [comment]
Bug fixed. Now searching for empty space will return a search result page asking users to enter valid input.
