### ISSUE TITLE
[MINOR] Search icon in search bar does not illustrate clickability on hover

### ISSUE THREAD

**Issue by anthonyqcn** [CourseVisor/CourseVisor#52]
**Describe the bug**
When searching for a course, you're able to click on the magnifying glass search icon as an equivalent to pressing enter. However, when you hover over the search icon there's no indicator that it actually is clickable, which is a usability issue because users who would rather click than type enter wouldn't know they're able to click unless they try it anyway which can be misleading.

**To Reproduce**

- Go to 'https://coursevisor.firebaseapp.com/'
- Click on the search bar to focus on it
- Hover over the magnifying glass in the search bar

**Expected behavior**
Although the cursor changes from input text to default icon, it'd be more helpful for it to display the clickable interaction cursor instead.

**Comment by albertli354** [comment]
Bug fixed. Users now have hover over effect for search icon.
