### ISSUE TITLE
[MINOR]Not going back to the previous state after sign in

### ISSUE THREAD

**Issue by lyuyueCC** [CourseVisor/CourseVisor#53]
- Description of the failure:
It is very accepted and necessary that the user should sign in to search for results. However, I would be more satisfied if I can go back to the previous state after I have successfully signed in.
- Reproduction steps:
1. Go to the home page and stay logged out
2. Search something in the search box in homepage
3. A warning window pops up indicating that the user can only search for results if signed in
4. Successfully signed in
5. Going back to the homepage while the result for the previous search is expected.
- Clear rationale:
From my user experience perspective, this could save much work and time for me.

**Comment by albertli354** [comment]
### Unreproducible

I followed your steps, but could not reproduce the bugs you described. I followed your step 1 to 3, but did not see any warnings that do not allow users to search if they are not logged in. The website allows users to search for reviews even if they are not signed in. 
![image](https://user-images.githubusercontent.com/26781751/70480433-8a89f380-1a94-11ea-9520-3e148c66930c.png)
